import { NextResponse } from "next/server";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";
import jwt from "jsonwebtoken";
import mongoose from "mongoose";
import puppeteer from "puppeteer";
import puppeteerCore from "puppeteer-core";
import chromium from "@sparticuz/chromium";
import dbConnect from "@/lib/mongodb";
import SRSForm from "@/models/SRSForm";
import { generateSimplePDF } from "@/lib/simplePdfGenerator";

const JWT_SECRET = process.env.JWT_SECRET;

export async function POST(req) {
  try {
    const { markdown, docId, title = "SpecForge SRS Document", subtitle = "Generated by SpecForge AI", author = "", date = new Date().toLocaleDateString() } = await req.json();

    let mdContent = markdown;

    if ((!mdContent || !mdContent.trim()) && docId) {
      const authHeader = req.headers.get("authorization");
      if (!authHeader?.startsWith("Bearer ")) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }

      const token = authHeader.split(" ")[1];
      const decoded = jwt.verify(token, JWT_SECRET);

      if (!mongoose.Types.ObjectId.isValid(docId)) {
        return NextResponse.json({ error: "Invalid document ID" }, { status: 400 });
      }

      await dbConnect();
      const document = await SRSForm.findById(docId);
      if (!document) {
        return NextResponse.json({ error: "Document not found" }, { status: 404 });
      }

      const userId = decoded.id;
      const isOwner = document.createdBy?.toString() === userId;
      const isCollaborator = Array.isArray(document.collaborators)
        ? document.collaborators.some((c) => c.userId?.toString() === userId)
        : false;

      if (!isOwner && !isCollaborator) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
      }

      mdContent = document.markdown || "";

      if (!mdContent.trim()) {
        mdContent = `# ${document.projectName || "SRS Document"}\n\n## 1. Purpose\n${document.purpose || "-"}\n\n## 2. Scope\n${document.scope || "-"}\n\n## 3. Notes\n${document.notes || "-"}`;
      }
    }

    if (!mdContent) return NextResponse.json({ error: "No markdown provided" }, { status: 400 });

    // Convert Markdown to HTML and sanitize
    const htmlContent = marked(mdContent);
    const cleanHtml = sanitizeHtml(htmlContent);

    // Professional HTML template for clean business-style PDFs
    const fullHtml = `<!doctype html><html><head>
      <meta charset='utf-8' />
      <meta name='viewport' content='width=device-width,initial-scale=1' />
      <link href='https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700;800&family=Source+Serif+4:wght@400;600&display=swap' rel='stylesheet'>
      <style>
        body { font-family: 'Source Serif 4', serif; color: #111827; background: #fff; padding: 0; }
        .pdf-container { max-width: 820px; margin: 0 auto; background: #fff; padding: 42px 44px 30px 44px; }
        .cover {
          margin-bottom: 42px;
          padding: 32px;
          border: 1px solid #dbe3f0;
          border-radius: 18px;
          background: linear-gradient(160deg, #f8fbff 0%, #eef6ff 58%, #ffffff 100%);
        }
        .brand { font: 700 14px/1 'Manrope', sans-serif; letter-spacing: 0.1em; color: #0369a1; text-transform: uppercase; }
        .cover h1 { font: 800 34px/1.15 'Manrope', sans-serif; margin: 12px 0 8px; color: #0f172a; letter-spacing: 0.01em; }
        .cover p { font: 600 16px/1.4 'Manrope', sans-serif; color: #334155; margin: 0 0 6px; }
        .meta { margin-top: 18px; font: 500 12px/1.6 'Manrope', sans-serif; color: #475569; }
        h1, h2, h3, h4 { font-family: 'Manrope', sans-serif; color: #0f172a; margin-top: 26px; margin-bottom: 8px; page-break-after: avoid; }
        h1 { font-size: 28px; border-bottom: 2px solid #dbeafe; padding-bottom: 8px; }
        h2 { font-size: 22px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
        h3 { font-size: 18px; color: #0c4a6e; }
        h4 { font-size: 16px; color: #1e3a8a; }
        p, li { font-size: 14px; line-height: 1.75; margin-bottom: 8px; color: #1f2937; }
        ul, ol { margin-left: 22px; margin-bottom: 12px; }
        strong { color: #0f172a; font-weight: 700; }
        em { color: #334155; }
        pre, code { font-family: ui-monospace, Menlo, Consolas, monospace; }
        code { font-size: 12px; background: #f1f5f9; color: #0f172a; padding: 2px 6px; border-radius: 6px; }
        pre { margin: 16px 0; padding: 12px; border-radius: 10px; border: 1px solid #e2e8f0; background: #f8fafc; overflow: hidden; page-break-inside: avoid; }
        pre code { background: transparent; padding: 0; }
        blockquote {
          margin: 14px 0;
          padding: 10px 14px;
          border-left: 4px solid #0ea5e9;
          background: #eff6ff;
          color: #334155;
          border-radius: 6px;
        }
        img { max-width: 100%; margin: 16px 0; border-radius: 10px; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 13px; page-break-inside: avoid; }
        th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; vertical-align: top; }
        th { background: #e0f2fe; color: #0c4a6e; font-family: 'Manrope', sans-serif; font-weight: 700; }
        tr:nth-child(even) { background: #f8fafc; }
        .footer { text-align: center; font: 500 11px/1.5 'Manrope', sans-serif; color: #64748b; margin-top: 24px; }
        @media print {
          body { background: #fff; }
          .pdf-container { box-shadow: none; border-radius: 0; }
        }
      </style>
    </head><body>
      <div class='pdf-container'>
        <div class='cover'>
          <div class='brand'>SpecForge</div>
          <h1>${title}</h1>
          <p>${subtitle}</p>
          <div class='meta'>${author ? `Author: ${author} | ` : ""}Date: ${date}</div>
        </div>
        <main>${cleanHtml}</main>
        <div class='footer'>
          Generated by SpecForge • ${new Date().getFullYear()}
        </div>
      </div>
    </body></html>`;

    let pdfBuffer;

    try {
      // Use chromium + puppeteer-core on Vercel, regular puppeteer elsewhere.
      const isVercel = !!process.env.VERCEL;
      const browser = isVercel
        ? await puppeteerCore.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath(),
            headless: chromium.headless,
          })
        : await puppeteer.launch({
            headless: true,
            args: ["--no-sandbox", "--disable-setuid-sandbox"],
          });

      try {
        const page = await browser.newPage();
        await page.setContent(fullHtml, { waitUntil: "domcontentloaded" });
        pdfBuffer = await page.pdf({
          format: "A4",
          printBackground: true,
          margin: { top: "18mm", bottom: "20mm", left: "14mm", right: "14mm" },
          displayHeaderFooter: true,
          headerTemplate: `<div></div>`,
          footerTemplate: `<div style='font-size:9px;width:100%;text-align:center;color:#64748b;letter-spacing:.02em;'><span class='pageNumber'></span> / <span class='totalPages'></span></div>`,
        });
      } finally {
        await browser.close();
      }
    } catch (pdfEngineError) {
      console.error("Primary PDF engine failed, using fallback:", pdfEngineError);
      pdfBuffer = await generateSimplePDF(mdContent, title || "SpecForge-SRS");
    }

    // Return PDF as response
    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/\s+/g, "_")}.pdf"`
      }
    });
  } catch (err) {
    console.error("PDF generation error:", err);
    return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
  }
}
