import { NextResponse } from "next/server";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";
import puppeteer from "puppeteer-core";
import chromium from "@sparticuz/chromium";
import { promises as fs } from "fs";

// Optional: import your SRSForm model if you want to fetch markdown by docId
// import SRSForm from "../../../models/SRSForm";

export async function POST(req) {
  try {
    const { markdown, docId, title = "SpecForge SRS Document", subtitle = "Generated by SpecForge AI", author = "", date = new Date().toLocaleDateString() } = await req.json();

    let mdContent = markdown;
    // If docId is provided, fetch markdown from DB (uncomment and adapt as needed)
    // if (docId) {
    //   const doc = await SRSForm.findById(docId);
    //   if (!doc) return NextResponse.json({ error: "Document not found" }, { status: 404 });
    //   mdContent = doc.markdown;
    // }
    if (!mdContent) return NextResponse.json({ error: "No markdown provided" }, { status: 400 });

    // Convert Markdown to HTML and sanitize
    const htmlContent = marked(mdContent);
    const cleanHtml = sanitizeHtml(htmlContent);

    // Professional HTML template (upgraded)
    const fullHtml = `<!doctype html><html><head>
      <meta charset='utf-8' />
      <meta name='viewport' content='width=device-width,initial-scale=1' />
      <link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap' rel='stylesheet'>
      <style>
        body { font-family: 'Inter', Arial, sans-serif; color: #18181b; background: #fff; padding: 0; }
        .pdf-container { max-width: 800px; margin: 0 auto; background: #fff; border-radius: 0; box-shadow: none; padding: 48px 48px 32px 48px; }
        .cover { text-align: center; margin-bottom: 48px; padding-bottom: 32px; border-bottom: 2px solid #e0e7ef; }
        .cover h1 { font-size: 2.8em; font-weight: 700; margin-bottom: 0.2em; color: #18181b; letter-spacing: 0.02em; }
        .cover p { font-size: 1.3em; color: #555; margin-bottom: 0.5em; }
        .meta { font-size: 1em; color: #888; margin-bottom: 12px; }
        h1, h2, h3, h4 { font-weight: 700; color: #18181b; margin-top: 32px; margin-bottom: 10px; }
        h1 { font-size: 2em; }
        h2 { font-size: 1.5em; }
        h3 { font-size: 1.2em; }
        h4 { font-size: 1.1em; }
        p, li { font-size: 1.05em; line-height: 1.8; margin-bottom: 8px; font-weight: 400; color: #222; }
        ul, ol { margin-left: 28px; margin-bottom: 12px; }
        ul li, ol li { margin-bottom: 6px; }
        pre, code { background: none; font-family: 'Inter', monospace; padding: 0; border-radius: 0; font-size: 1em; color: #222; }
        pre { margin-bottom: 16px; }
        img { max-width: 100%; margin: 16px 0; border-radius: 8px; }
        table { border-collapse: collapse; width: 100%; margin: 18px 0; }
        th, td { border: 1px solid #e0e7ef; padding: 8px 12px; text-align: left; }
        th { background: #f1f5f9; font-weight: 600; }
        .page-break { page-break-before: always; }
        .footer { text-align: center; font-size: 0.95em; color: #94a3b8; margin-top: 32px; }
        @media print {
          body { background: #fff; }
          .pdf-container { box-shadow: none; border-radius: 0; padding: 0; }
        }
      </style>
    </head><body>
      <div class='pdf-container'>
        <div class='cover'>
          <h1>${title}</h1>
          <p>${subtitle}</p>
          <div class='meta'>${author ? `Author: ${author} | ` : ""}Date: ${date}</div>
        </div>
        <main>${cleanHtml}</main>
        <div class='footer'>
          Generated by SpecForge • ${new Date().getFullYear()}
        </div>
      </div>
    </body></html>`;

    // Generate PDF with Puppeteer (serverless-compatible)
    const browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });
    const page = await browser.newPage();
    await page.setContent(fullHtml, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "24mm", bottom: "24mm", left: "18mm", right: "18mm" },
      displayHeaderFooter: true,
      headerTemplate: `<div></div>`,
      footerTemplate: `<div style='font-size:9px;width:100%;text-align:center;color:#888;'><span class='pageNumber'></span> / <span class='totalPages'></span></div>`
    });
    await browser.close();

    // Return PDF as response
    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/\s+/g, "_")}.pdf"`
      }
    });
  } catch (err) {
    console.error("PDF generation error:", err);
    return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
  }
}
